name: Build
on:
  push:
    branches: [opensource]
  pull_request:
    branches: [opensource]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile and bundle dmg
        run: |
          xcodebuild -target BetterDisplayHelper -project BetterDisplay.xcodeproj CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          xcodebuild -target BetterDisplay -project BetterDisplay.xcodeproj CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          hdiutil create BetterDisplay-uncompressed.dmg -volname "BetterDisplay" -srcfolder ./build/Release/BetterDisplay.app
          hdiutil convert BetterDisplay-uncompressed.dmg -format UDZO -o BetterDisplay.dmg
      - uses: actions/upload-artifact@v2
        with:
          name: BetterDisplay.dmg
          path: BetterDisplay.dmg
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: BetterDisplay.dmg
          tag: ${{ github.ref }}
          file_glob: true